import { ElementRef, NgZone, EventEmitter, TemplateRef, Renderer, OnDestroy } from '@angular/core';
import { Select } from './../common/select';
import { SelectService } from "../service/select.service";
export declare class RequestMultipleComponent extends Select implements OnDestroy {
    elementRef: ElementRef;
    zone: NgZone;
    requisicao: SelectService;
    renderer: Renderer;
    name: any;
    classe: any;
    placeholder: string;
    minimoCaracteres: number;
    templateResultado: TemplateRef<any>;
    templateSelecionado: TemplateRef<any>;
    templateSemResultado: TemplateRef<any>;
    templateBuscando: TemplateRef<any>;
    indiceId: string;
    indiceNome: string;
    url: string;
    change: EventEmitter<any>;
    onSelecionarItem: EventEmitter<any>;
    onBuscar: EventEmitter<any>;
    onApagar: EventEmitter<any>;
    onRemoverItem: EventEmitter<any>;
    onAbrir: EventEmitter<any>;
    onFechar: EventEmitter<any>;
    onLimpar: EventEmitter<any>;
    onErro: EventEmitter<any>;
    onProcessaResultado: EventEmitter<any>;
    onProcessaParametros: EventEmitter<any>;
    campoBusca: ElementRef;
    private pagina;
    private quantidadePadrao;
    private buscando;
    private semResultado;
    private subscrebeBusca;
    constructor(elementRef: ElementRef, zone: NgZone, requisicao: SelectService, renderer: Renderer);
    ngOnDestroy(): void;
    abrir(): void;
    keyup(valor: any): any;
    selecionar(item: any): void;
    getSomenteId(): any[];
    limpar(): void;
    buscar(): boolean;
    onScroll(): void;
    value: any;
}
