/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './multiple.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '@angular/core/src/linker/element_ref';
import * as import10 from '@angular/core/src/zone/ng_zone';
import * as import11 from '@angular/forms/src/directives/control_value_accessor';
import * as import12 from '../directive/highlight.directive.ngfactory';
import * as import13 from '@angular/core/src/linker/view_container';
import * as import14 from '../directive/inner-template.directive.ngfactory';
import * as import15 from '../directive/inner-template.directive';
import * as import16 from '../directive/highlight.directive';
import * as import17 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import18 from '@angular/core/src/linker/template_ref';
import * as import19 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import20 from '@angular/common/src/directives/ng_for';
import * as import21 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import22 from '@angular/common/src/directives/ng_if';
import * as import23 from '@angular/core/src/linker/query_list';
import * as import24 from '../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import25 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import26 from '@angular/common/src/directives/ng_class';
import * as import27 from '@angular/core/src/security';
export class Wrapper_MultipleComponent {
  /*private*/ _eventHandler:Function;
  context:import0.MultipleComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  subscription0:any;
  subscription1:any;
  subscription2:any;
  subscription3:any;
  subscription4:any;
  subscription5:any;
  subscription6:any;
  subscription7:any;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.MultipleComponent(p0,p1);
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
    this._expr_2 = import1.UNINITIALIZED;
    this._expr_3 = import1.UNINITIALIZED;
    this._expr_4 = import1.UNINITIALIZED;
    this._expr_5 = import1.UNINITIALIZED;
    this._expr_6 = import1.UNINITIALIZED;
    this._expr_7 = import1.UNINITIALIZED;
    this._expr_8 = import1.UNINITIALIZED;
    this._expr_9 = import1.UNINITIALIZED;
    this._expr_10 = import1.UNINITIALIZED;
    this._expr_11 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
    (this.subscription1 && this.subscription1.unsubscribe());
    (this.subscription2 && this.subscription2.unsubscribe());
    (this.subscription3 && this.subscription3.unsubscribe());
    (this.subscription4 && this.subscription4.unsubscribe());
    (this.subscription5 && this.subscription5.unsubscribe());
    (this.subscription6 && this.subscription6.unsubscribe());
    (this.subscription7 && this.subscription7.unsubscribe());
  }
  check_name(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.name = currValue;
      this._expr_0 = currValue;
    }
  }
  check_classe(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.classe = currValue;
      this._expr_1 = currValue;
    }
  }
  check_placeholder(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_2,currValue))) {
      this._changed = true;
      this.context.placeholder = currValue;
      this._expr_2 = currValue;
    }
  }
  check_minimoCaracteres(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_3,currValue))) {
      this._changed = true;
      this.context.minimoCaracteres = currValue;
      this._expr_3 = currValue;
    }
  }
  check_templateResultado(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_4,currValue))) {
      this._changed = true;
      this.context.templateResultado = currValue;
      this._expr_4 = currValue;
    }
  }
  check_templateSelecionado(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_5,currValue))) {
      this._changed = true;
      this.context.templateSelecionado = currValue;
      this._expr_5 = currValue;
    }
  }
  check_templateSemResultado(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_6,currValue))) {
      this._changed = true;
      this.context.templateSemResultado = currValue;
      this._expr_6 = currValue;
    }
  }
  check_disabled(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_7,currValue))) {
      this._changed = true;
      this.context.disabled = currValue;
      this._expr_7 = currValue;
    }
  }
  check_indiceId(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_8,currValue))) {
      this._changed = true;
      this.context.indiceId = currValue;
      this._expr_8 = currValue;
    }
  }
  check_indiceNome(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_9,currValue))) {
      this._changed = true;
      this.context.indiceNome = currValue;
      this._expr_9 = currValue;
    }
  }
  check_valores(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_10,currValue))) {
      this._changed = true;
      this.context.valores = currValue;
      this._expr_10 = currValue;
    }
  }
  check_value(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_11,currValue))) {
      this._changed = true;
      this.context.value = currValue;
      this._expr_11 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    if ((eventName == 'document:click')) {
      const pd_sub_0:any = ((<any>this.context.clickForaComponent($event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'focus')) {
      const pd_sub_1:any = ((<any>this.context.setFocus(true)) !== false);
      result = (pd_sub_1 && result);
    }
    if ((eventName == 'blur')) {
      const pd_sub_2:any = ((<any>this.context.setFocus(false)) !== false);
      result = (pd_sub_2 && result);
    }
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean,emit1:boolean,emit2:boolean,emit3:boolean,emit4:boolean,emit5:boolean,emit6:boolean,emit7:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.change.subscribe(_eventHandler.bind(view,'change'))); }
    if (emit1) { (this.subscription1 = this.context.onSelecionarItem.subscribe(_eventHandler.bind(view,'onSelecionarItem'))); }
    if (emit2) { (this.subscription2 = this.context.onBuscar.subscribe(_eventHandler.bind(view,'onBuscar'))); }
    if (emit3) { (this.subscription3 = this.context.onApagar.subscribe(_eventHandler.bind(view,'onApagar'))); }
    if (emit4) { (this.subscription4 = this.context.onRemoverItem.subscribe(_eventHandler.bind(view,'onRemoverItem'))); }
    if (emit5) { (this.subscription5 = this.context.onAbrir.subscribe(_eventHandler.bind(view,'onAbrir'))); }
    if (emit6) { (this.subscription6 = this.context.onFechar.subscribe(_eventHandler.bind(view,'onFechar'))); }
    if (emit7) { (this.subscription7 = this.context.onLimpar.subscribe(_eventHandler.bind(view,'onLimpar'))); }
  }
}
var renderType_MultipleComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_MultipleComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.MultipleComponent>;
  _MultipleComponent_0_3:Wrapper_MultipleComponent;
  __NG_VALUE_ACCESSOR_0_4:any[];
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_MultipleComponent_Host0,renderType_MultipleComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  get _NG_VALUE_ACCESSOR_0_4():any[] {
    if ((this.__NG_VALUE_ACCESSOR_0_4 == null)) { (this.__NG_VALUE_ACCESSOR_0_4 = [this._MultipleComponent_0_3.context]); }
    return this.__NG_VALUE_ACCESSOR_0_4;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'select2-multiple',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_MultipleComponent0(this.viewUtils,this,0,this._el_0);
    this._MultipleComponent_0_3 = new Wrapper_MultipleComponent(new import9.ElementRef(this._el_0),this.injectorGet(import10.NgZone,this.parentIndex));
    this.compView_0.create(this._MultipleComponent_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray8(6,'click','document','focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._MultipleComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.MultipleComponent) && (0 === requestNodeIndex))) { return this._MultipleComponent_0_3.context; }
    if (((token === import11.NG_VALUE_ACCESSOR) && (0 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MultipleComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._MultipleComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.compView_0.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MultipleComponent_0_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
export const MultipleComponentNgFactory:import8.ComponentFactory<import0.MultipleComponent> = new import8.ComponentFactory<import0.MultipleComponent>('select2-multiple',View_MultipleComponent_Host0,import0.MultipleComponent);
const styles_MultipleComponent:any[] = ([] as any[]);
class View_MultipleComponent1 extends import2.AppView<any> {
  _el_0:any;
  _HighlightDirective_0_3:import12.Wrapper_HighlightDirective;
  _text_1:any;
  _el_2:any;
  /*private*/ _vc_2:import13.ViewContainer;
  _InnerTemplateDirective_2_5:import14.Wrapper_InnerTemplateDirective;
  _text_3:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_MultipleComponent1,renderType_MultipleComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_7 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',new import3.InlineArray8(6,'class','select2-results__option','highlight','select2-results__option--highlighted','role','treeitem'),(null as any));
    this._HighlightDirective_0_3 = new import12.Wrapper_HighlightDirective(new import9.ElementRef(this._el_0));
    this._text_1 = this.renderer.createText(this._el_0,'\n                                    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_2 = new import13.ViewContainer(2,0,this,this._el_2);
    this._InnerTemplateDirective_2_5 = new import14.Wrapper_InnerTemplateDirective(this._vc_2.vcRef);
    this._text_3 = this.renderer.createText(this._el_0,'\n                                ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray8(6,'click',(null as any),'mouseenter',(null as any),'mouseleave',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.InnerTemplateDirective) && (2 === requestNodeIndex))) { return this._InnerTemplateDirective_2_5.context; }
    if (((token === import16.HighlightDirective) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._HighlightDirective_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = 'select2-results__option--highlighted';
    this._HighlightDirective_0_3.check_classe(currVal_0_0_0,throwOnChange,false);
    this._HighlightDirective_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_2_0_0:any = this.context.$implicit;
    this._InnerTemplateDirective_2_5.check_item(currVal_2_0_0,throwOnChange,false);
    const currVal_2_0_1:any = (this.parentView.context.templateResultado || (<View_MultipleComponent0>this.parentView)._TemplateRef_65_4);
    this._InnerTemplateDirective_2_5.check_templateRef(currVal_2_0_1,throwOnChange,false);
    this._InnerTemplateDirective_2_5.ngDoCheck(this,this._el_2,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
    const currVal_7:any = ((this.parentView.context._value && (this.context.$implicit[this.parentView.context.indiceId] == this.parentView.context._value[this.parentView.context.indiceId]))? true: false);
    if (import3.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementAttribute(this._el_0,'aria-selected',((currVal_7 == null)? (null as any): currVal_7.toString()));
      this._expr_7 = currVal_7;
    }
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._HighlightDirective_0_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.selecionar(this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_MultipleComponent2 extends import2.AppView<any> {
  _text_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_MultipleComponent2,renderType_MultipleComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._text_0 = this.renderer.createText((null as any),'\n        Nenhum resultado encontrado\n    ',(null as any));
    this.init(this._text_0,((<any>this.renderer).directRenderer? (null as any): [this._text_0]),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._text_0,ctx);
  }
}
class View_MultipleComponent3 extends import2.AppView<any> {
  _text_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_MultipleComponent3,renderType_MultipleComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_1 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._text_0 = this.renderer.createText((null as any),'',(null as any));
    this.init(this._text_0,((<any>this.renderer).directRenderer? (null as any): [this._text_0]),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = import3.inlineInterpolate(1,'\n        ',this.context.$implicit[this.parentView.context.indiceNome],'\n    ');
    if (import3.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_0,currVal_1);
      this._expr_1 = currVal_1;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._text_0,ctx);
  }
}
class View_MultipleComponent6 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_MultipleComponent6,renderType_MultipleComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_5 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',new import3.InlineArray2(2,'class','select2-selection__choice'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'span',new import3.InlineArray4(4,'class','select2-selection__choice__remove','role','presentation'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'×',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_5:any = import3.inlineInterpolate(1,'\n                ',this.context.$implicit[this.parentView.parentView.parentView.context.indiceNome],'\n            ');
    if (import3.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_4,currVal_5);
      this._expr_5 = currVal_5;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.$implicit.remove(this.context.$implicit,$event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_MultipleComponent5 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import13.ViewContainer;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import17.Wrapper_NgFor;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_MultipleComponent5,renderType_MultipleComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import13.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import18.TemplateRef_(this,2,this._anchor_2);
    this._NgFor_2_6 = new import17.Wrapper_NgFor(this._vc_2.vcRef,this._TemplateRef_2_5,this.parentView.injectorGet(import19.IterableDiffers,this.parentIndex),this.parentView.parentView.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import20.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.parentView.context.$implicit.data;
    this._NgFor_2_6.check_ngForOf(currVal_2_0_0,throwOnChange,false);
    this._NgFor_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 2)) { return new View_MultipleComponent6(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    return (null as any);
  }
}
class View_MultipleComponent4 extends import2.AppView<any> {
  _text_0:any;
  _anchor_1:any;
  /*private*/ _vc_1:import13.ViewContainer;
  _TemplateRef_1_5:any;
  _NgIf_1_6:import21.Wrapper_NgIf;
  _text_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_MultipleComponent4,renderType_MultipleComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._text_0 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._anchor_1 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._vc_1 = new import13.ViewContainer(1,(null as any),this,this._anchor_1);
    this._TemplateRef_1_5 = new import18.TemplateRef_(this,1,this._anchor_1);
    this._NgIf_1_6 = new import21.Wrapper_NgIf(this._vc_1.vcRef,this._TemplateRef_1_5);
    this._text_2 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.init(this._text_2,((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._anchor_1,
      this._text_2
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.TemplateRef) && (1 === requestNodeIndex))) { return this._TemplateRef_1_5; }
    if (((token === import22.NgIf) && (1 === requestNodeIndex))) { return this._NgIf_1_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1_0_0:any = this.context.$implicit;
    this._NgIf_1_6.check_ngIf(currVal_1_0_0,throwOnChange,false);
    this._NgIf_1_6.ngDoCheck(this,this._anchor_1,throwOnChange);
    this._vc_1.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_1.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._text_0,ctx);
    cb(this._vc_1.nativeElement,ctx);
    this._vc_1.visitNestedViewRootNodes(cb,ctx);
    cb(this._text_2,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 1)) { return new View_MultipleComponent5(this.viewUtils,this,1,this._anchor_1,this._vc_1); }
    return (null as any);
  }
}
var renderType_MultipleComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,styles_MultipleComponent,{});
export class View_MultipleComponent0 extends import2.AppView<import0.MultipleComponent> {
  _viewQuery_campoBusca_0:import23.QueryList<any>;
  _text_0:any;
  _text_1:any;
  _el_2:any;
  _NgClass_2_3:import24.Wrapper_NgClass;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _vc_14:import13.ViewContainer;
  _InnerTemplateDirective_14_5:import14.Wrapper_InnerTemplateDirective;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _anchor_46:any;
  /*private*/ _vc_46:import13.ViewContainer;
  _TemplateRef_46_5:any;
  _NgFor_46_6:import17.Wrapper_NgFor;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _el_51:any;
  /*private*/ _vc_51:import13.ViewContainer;
  _InnerTemplateDirective_51_5:import14.Wrapper_InnerTemplateDirective;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _anchor_63:any;
  /*private*/ _vc_63:import13.ViewContainer;
  _TemplateRef_63_4:any;
  _text_64:any;
  _anchor_65:any;
  /*private*/ _vc_65:import13.ViewContainer;
  _TemplateRef_65_4:any;
  _text_66:any;
  _anchor_67:any;
  /*private*/ _vc_67:import13.ViewContainer;
  _TemplateRef_67_4:any;
  _text_68:any;
  /*private*/ _expr_84:any;
  /*private*/ _expr_85:any;
  /*private*/ _expr_86:any;
  /*private*/ _expr_87:any;
  /*private*/ _expr_88:any;
  /*private*/ _expr_89:any;
  /*private*/ _expr_90:any;
  _map_91:any;
  /*private*/ _expr_92:any;
  /*private*/ _expr_93:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_MultipleComponent0,renderType_MultipleComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_84 = import1.UNINITIALIZED;
    this._expr_85 = import1.UNINITIALIZED;
    this._expr_86 = import1.UNINITIALIZED;
    this._expr_87 = import1.UNINITIALIZED;
    this._expr_88 = import1.UNINITIALIZED;
    this._expr_89 = import1.UNINITIALIZED;
    this._expr_90 = import1.UNINITIALIZED;
    this._map_91 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {pesquisa: p0};
    });
    this._expr_92 = import1.UNINITIALIZED;
    this._expr_93 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._viewQuery_campoBusca_0 = new import23.QueryList<any>();
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,parentRenderNode,'span',new import3.InlineArray2(2,'dir','ltr'),(null as any));
    this._NgClass_2_3 = new import24.Wrapper_NgClass(this.parentView.injectorGet(import19.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import25.KeyValueDiffers,this.parentIndex),new import9.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'span',new import3.InlineArray2(2,'class','selection'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'span',new import3.InlineArray16(10,'aria-expanded','false','aria-haspopup','true','class','select2-selection select2-selection--multiple','role','combobox','tabindex','-1'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'ul',new import3.InlineArray2(2,'class','select2-selection__rendered'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'li',new import3.InlineArray2(2,'class','select2-selection__placeholder'),(null as any));
    this._text_11 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_8,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n                    ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_12,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_14 = new import13.ViewContainer(14,12,this,this._el_14);
    this._InnerTemplateDirective_14_5 = new import14.Wrapper_InnerTemplateDirective(this._vc_14.vcRef);
    this._text_15 = this.renderer.createText(this._el_12,'\n                ',(null as any));
    this._text_16 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_8,'li',new import3.InlineArray4(4,'class','select2-selection__arrow','role','presentation'),(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_17,'b',new import3.InlineArray2(2,'role','presentation'),(null as any));
    this._text_19 = this.renderer.createText(this._el_8,'\n            ',(null as any));
    this._text_20 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._text_21 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_22 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_2,'span',new import3.InlineArray4(4,'aria-hidden','true','class','dropdown-wrapper'),(null as any));
    this._text_24 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_25 = this.renderer.createText(parentRenderNode,'\n    \n    ',(null as any));
    this._text_26 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,parentRenderNode,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n        ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_27,'span',new import3.InlineArray2(2,'class','select2-container select2-container--bootstrap select2-container--open'),(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'\n            ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_29,'span',new import3.InlineArray4(4,'class','select2-dropdown select2-dropdown--below','dir','ltr'),(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'\n                ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_31,'span',new import3.InlineArray2(2,'class','select2-search select2-search--dropdown'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'\n                    ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_33,'input',new import3.InlineArrayDynamic(20,'autocapitalize','off','autocomplete','off','autocorrect','off','autofocus','','class','select2-search__field','placeholder','Digite algo','role','textbox','spellcheck','false','tabindex','0','type','search'),(null as any));
    this._text_36 = this.renderer.createText(this._el_33,'\n                ',(null as any));
    this._text_37 = this.renderer.createText(this._el_31,'\n                ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_31,'span',new import3.InlineArray2(2,'class','select2-results'),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'\n                    ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_38,'ul',new import3.InlineArray8(8,'aria-expanded','true','aria-hidden','false','class','select2-results__options','role','tree'),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'\n                        ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_40,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'\n                            ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_42,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'\n                                ',(null as any));
    this._anchor_46 = this.renderer.createTemplateAnchor(this._el_44,(null as any));
    this._vc_46 = new import13.ViewContainer(46,44,this,this._anchor_46);
    this._TemplateRef_46_5 = new import18.TemplateRef_(this,46,this._anchor_46);
    this._NgFor_46_6 = new import17.Wrapper_NgFor(this._vc_46.vcRef,this._TemplateRef_46_5,this.parentView.injectorGet(import19.IterableDiffers,this.parentIndex),this.ref);
    this._text_47 = this.renderer.createText(this._el_44,'\n                            ',(null as any));
    this._text_48 = this.renderer.createText(this._el_42,'\n                            ',(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,this._el_42,'li',new import3.InlineArray4(4,'aria-live','assertive','class','select2-results__option select2-results__message'),(null as any));
    this._text_50 = this.renderer.createText(this._el_49,'\n                                ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_49,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_51 = new import13.ViewContainer(51,49,this,this._el_51);
    this._InnerTemplateDirective_51_5 = new import14.Wrapper_InnerTemplateDirective(this._vc_51.vcRef);
    this._text_52 = this.renderer.createText(this._el_49,'\n                            ',(null as any));
    this._text_53 = this.renderer.createText(this._el_42,'\n                        ',(null as any));
    this._text_54 = this.renderer.createText(this._el_40,'\n                        ',(null as any));
    this._el_55 = import3.createRenderElement(this.renderer,this._el_40,'li',new import3.InlineArray2(2,'class','select2-results__option select2-results__message'),(null as any));
    this._text_56 = this.renderer.createText(this._el_55,'',(null as any));
    this._text_57 = this.renderer.createText(this._el_40,'\n                    ',(null as any));
    this._text_58 = this.renderer.createText(this._el_38,'\n                ',(null as any));
    this._text_59 = this.renderer.createText(this._el_31,'\n            ',(null as any));
    this._text_60 = this.renderer.createText(this._el_29,'\n        ',(null as any));
    this._text_61 = this.renderer.createText(this._el_27,'\n    ',(null as any));
    this._text_62 = this.renderer.createText(parentRenderNode,'\n    \n    \n    \n    ',(null as any));
    this._anchor_63 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_63 = new import13.ViewContainer(63,(null as any),this,this._anchor_63);
    this._TemplateRef_63_4 = new import18.TemplateRef_(this,63,this._anchor_63);
    this._text_64 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._anchor_65 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_65 = new import13.ViewContainer(65,(null as any),this,this._anchor_65);
    this._TemplateRef_65_4 = new import18.TemplateRef_(this,65,this._anchor_65);
    this._text_66 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._anchor_67 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_67 = new import13.ViewContainer(67,(null as any),this,this._anchor_67);
    this._TemplateRef_67_4 = new import18.TemplateRef_(this,67,this._anchor_67);
    this._text_68 = this.renderer.createText(parentRenderNode,'\n\n    \n    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_35,new import3.InlineArray2(2,'keyup',(null as any)),this.eventHandler(this.handleEvent_35));
    this._viewQuery_campoBusca_0.reset([new import9.ElementRef(this._el_35)]);
    this.context.campoBusca = this._viewQuery_campoBusca_0.first;
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._anchor_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._anchor_63,
      this._text_64,
      this._anchor_65,
      this._text_66,
      this._anchor_67,
      this._text_68
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.InnerTemplateDirective) && (14 === requestNodeIndex))) { return this._InnerTemplateDirective_14_5.context; }
    if (((token === import26.NgClass) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._NgClass_2_3.context; }
    if (((token === import18.TemplateRef) && (46 === requestNodeIndex))) { return this._TemplateRef_46_5; }
    if (((token === import20.NgFor) && (46 === requestNodeIndex))) { return this._NgFor_46_6.context; }
    if (((token === import15.InnerTemplateDirective) && (51 === requestNodeIndex))) { return this._InnerTemplateDirective_51_5.context; }
    if (((token === import18.TemplateRef) && (63 === requestNodeIndex))) { return this._TemplateRef_63_4; }
    if (((token === import18.TemplateRef) && (65 === requestNodeIndex))) { return this._TemplateRef_65_4; }
    if (((token === import18.TemplateRef) && (67 === requestNodeIndex))) { return this._TemplateRef_67_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.context.getClassGeral();
    this._NgClass_2_3.check_ngClass(currVal_2_0_0,throwOnChange,false);
    this._NgClass_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_14_0_0:any = this.context;
    this._InnerTemplateDirective_14_5.check_item(currVal_14_0_0,throwOnChange,false);
    const currVal_14_0_1:any = (this.context.templateSelecionado || this._TemplateRef_67_4);
    this._InnerTemplateDirective_14_5.check_templateRef(currVal_14_0_1,throwOnChange,false);
    this._InnerTemplateDirective_14_5.ngDoCheck(this,this._el_14,throwOnChange);
    const currVal_46_0_0:any = this.context.valoresExibir;
    this._NgFor_46_6.check_ngForOf(currVal_46_0_0,throwOnChange,false);
    this._NgFor_46_6.ngDoCheck(this,this._anchor_46,throwOnChange);
    const currVal_51_0_0:any = this._map_91(this.context.valorPesquisado);
    this._InnerTemplateDirective_51_5.check_item(currVal_51_0_0,throwOnChange,false);
    const currVal_51_0_1:any = (this.context.templateSemResultado || this._TemplateRef_63_4);
    this._InnerTemplateDirective_51_5.check_templateRef(currVal_51_0_1,throwOnChange,false);
    this._InnerTemplateDirective_51_5.ngDoCheck(this,this._el_51,throwOnChange);
    this._vc_14.detectChangesInNestedViews(throwOnChange);
    this._vc_46.detectChangesInNestedViews(throwOnChange);
    this._vc_51.detectChangesInNestedViews(throwOnChange);
    this._vc_63.detectChangesInNestedViews(throwOnChange);
    this._vc_65.detectChangesInNestedViews(throwOnChange);
    this._vc_67.detectChangesInNestedViews(throwOnChange);
    const currVal_84:any = this.context.data;
    if (import3.checkBinding(throwOnChange,this._expr_84,currVal_84)) {
      this.renderer.setElementProperty(this._el_10,'hidden',currVal_84);
      this._expr_84 = currVal_84;
    }
    const currVal_85:any = this.context.placeholder;
    if (import3.checkBinding(throwOnChange,this._expr_85,currVal_85)) {
      this.renderer.setElementProperty(this._el_10,'innerHTML',this.viewUtils.sanitizer.sanitize(import27.SecurityContext.HTML,currVal_85));
      this._expr_85 = currVal_85;
    }
    const currVal_86:boolean = !this.context.data;
    if (import3.checkBinding(throwOnChange,this._expr_86,currVal_86)) {
      this.renderer.setElementProperty(this._el_12,'hidden',currVal_86);
      this._expr_86 = currVal_86;
    }
    const currVal_87:boolean = !this.context.aberto;
    if (import3.checkBinding(throwOnChange,this._expr_87,currVal_87)) {
      this.renderer.setElementProperty(this._el_27,'hidden',currVal_87);
      this._expr_87 = currVal_87;
    }
    const currVal_88:any = this.context.exibirMensagemCaracteresMinimo;
    if (import3.checkBinding(throwOnChange,this._expr_88,currVal_88)) {
      this.renderer.setElementProperty(this._el_42,'hidden',currVal_88);
      this._expr_88 = currVal_88;
    }
    const currVal_89:any = (this.context.valoresExibir.length == 0);
    if (import3.checkBinding(throwOnChange,this._expr_89,currVal_89)) {
      this.renderer.setElementProperty(this._el_44,'hidden',currVal_89);
      this._expr_89 = currVal_89;
    }
    const currVal_90:any = (this.context.valoresExibir.length > 0);
    if (import3.checkBinding(throwOnChange,this._expr_90,currVal_90)) {
      this.renderer.setElementProperty(this._el_49,'hidden',currVal_90);
      this._expr_90 = currVal_90;
    }
    const currVal_92:any = (this.context.exibirMensagemCaracteresMinimo == false);
    if (import3.checkBinding(throwOnChange,this._expr_92,currVal_92)) {
      this.renderer.setElementProperty(this._el_55,'hidden',currVal_92);
      this._expr_92 = currVal_92;
    }
    const currVal_93:any = import3.inlineInterpolate(1,'\n                            Digite ',this.context.minimoCaracteres,' ou mais caracteres para realizar a busca\n                        ');
    if (import3.checkBinding(throwOnChange,this._expr_93,currVal_93)) {
      this.renderer.setText(this._text_56,currVal_93);
      this._expr_93 = currVal_93;
    }
  }
  destroyInternal():void {
    this._vc_14.destroyNestedViews();
    this._vc_46.destroyNestedViews();
    this._vc_51.destroyNestedViews();
    this._vc_63.destroyNestedViews();
    this._vc_65.destroyNestedViews();
    this._vc_67.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 46)) { return new View_MultipleComponent1(this.viewUtils,this,46,this._anchor_46,this._vc_46); }
    if ((nodeIndex == 63)) { return new View_MultipleComponent2(this.viewUtils,this,63,this._anchor_63,this._vc_63); }
    if ((nodeIndex == 65)) { return new View_MultipleComponent3(this.viewUtils,this,65,this._anchor_65,this._vc_65); }
    if ((nodeIndex == 67)) { return new View_MultipleComponent4(this.viewUtils,this,67,this._anchor_67,this._vc_67); }
    return (null as any);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.abrir()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_35(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'keyup')) {
      const pd_sub_0:any = ((<any>this.context.keyup($event.target.value)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}