/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './request.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '@angular/core/src/linker/element_ref';
import * as import10 from '@angular/core/src/zone/ng_zone';
import * as import11 from '../service/select.service';
import * as import12 from '@angular/forms/src/directives/control_value_accessor';
import * as import13 from '../directive/highlight.directive.ngfactory';
import * as import14 from '@angular/core/src/linker/view_container';
import * as import15 from '../directive/inner-template.directive.ngfactory';
import * as import16 from '../directive/inner-template.directive';
import * as import17 from '../directive/highlight.directive';
import * as import18 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import19 from '@angular/core/src/linker/template_ref';
import * as import20 from '@angular/common/src/directives/ng_if';
import * as import21 from '@angular/core/src/linker/query_list';
import * as import22 from '../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import23 from '../directive/infinite-scroll.directive.ngfactory';
import * as import24 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import25 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import26 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import27 from '@angular/common/src/directives/ng_class';
import * as import28 from '@angular/common/src/directives/ng_for';
import * as import29 from '../directive/infinite-scroll.directive';
import * as import30 from '@angular/core/src/security';
export class Wrapper_RequestComponent {
  /*private*/ _eventHandler:Function;
  context:import0.RequestComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  subscription0:any;
  subscription1:any;
  subscription2:any;
  subscription3:any;
  subscription4:any;
  subscription5:any;
  subscription6:any;
  subscription7:any;
  subscription8:any;
  subscription9:any;
  subscription10:any;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this._changed = false;
    this.context = new import0.RequestComponent(p0,p1,p2,p3);
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
    this._expr_2 = import1.UNINITIALIZED;
    this._expr_3 = import1.UNINITIALIZED;
    this._expr_4 = import1.UNINITIALIZED;
    this._expr_5 = import1.UNINITIALIZED;
    this._expr_6 = import1.UNINITIALIZED;
    this._expr_7 = import1.UNINITIALIZED;
    this._expr_8 = import1.UNINITIALIZED;
    this._expr_9 = import1.UNINITIALIZED;
    this._expr_10 = import1.UNINITIALIZED;
    this._expr_11 = import1.UNINITIALIZED;
    this._expr_12 = import1.UNINITIALIZED;
    this._expr_13 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    this.context.ngOnDestroy();
    (this.subscription0 && this.subscription0.unsubscribe());
    (this.subscription1 && this.subscription1.unsubscribe());
    (this.subscription2 && this.subscription2.unsubscribe());
    (this.subscription3 && this.subscription3.unsubscribe());
    (this.subscription4 && this.subscription4.unsubscribe());
    (this.subscription5 && this.subscription5.unsubscribe());
    (this.subscription6 && this.subscription6.unsubscribe());
    (this.subscription7 && this.subscription7.unsubscribe());
    (this.subscription8 && this.subscription8.unsubscribe());
    (this.subscription9 && this.subscription9.unsubscribe());
    (this.subscription10 && this.subscription10.unsubscribe());
  }
  check_name(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.name = currValue;
      this._expr_0 = currValue;
    }
  }
  check_classe(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.classe = currValue;
      this._expr_1 = currValue;
    }
  }
  check_tabIndex(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_2,currValue))) {
      this._changed = true;
      this.context.tabIndex = currValue;
      this._expr_2 = currValue;
    }
  }
  check_minimoCaracteres(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_3,currValue))) {
      this._changed = true;
      this.context.minimoCaracteres = currValue;
      this._expr_3 = currValue;
    }
  }
  check_placeholder(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_4,currValue))) {
      this._changed = true;
      this.context.placeholder = currValue;
      this._expr_4 = currValue;
    }
  }
  check_templateResultado(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_5,currValue))) {
      this._changed = true;
      this.context.templateResultado = currValue;
      this._expr_5 = currValue;
    }
  }
  check_templateSelecionado(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_6,currValue))) {
      this._changed = true;
      this.context.templateSelecionado = currValue;
      this._expr_6 = currValue;
    }
  }
  check_templateSemResultado(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_7,currValue))) {
      this._changed = true;
      this.context.templateSemResultado = currValue;
      this._expr_7 = currValue;
    }
  }
  check_templateBuscando(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_8,currValue))) {
      this._changed = true;
      this.context.templateBuscando = currValue;
      this._expr_8 = currValue;
    }
  }
  check_disabled(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_9,currValue))) {
      this._changed = true;
      this.context.disabled = currValue;
      this._expr_9 = currValue;
    }
  }
  check_indiceId(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_10,currValue))) {
      this._changed = true;
      this.context.indiceId = currValue;
      this._expr_10 = currValue;
    }
  }
  check_indiceNome(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_11,currValue))) {
      this._changed = true;
      this.context.indiceNome = currValue;
      this._expr_11 = currValue;
    }
  }
  check_url(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_12,currValue))) {
      this._changed = true;
      this.context.url = currValue;
      this._expr_12 = currValue;
    }
  }
  check_value(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_13,currValue))) {
      this._changed = true;
      this.context.value = currValue;
      this._expr_13 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    if ((eventName == 'document:click')) {
      const pd_sub_0:any = ((<any>this.context.clickForaComponent($event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'focus')) {
      const pd_sub_1:any = ((<any>this.context.abrir()) !== false);
      result = (pd_sub_1 && result);
    }
    if ((eventName == 'blur')) {
      const pd_sub_2:any = ((<any>this.context.fechar()) !== false);
      result = (pd_sub_2 && result);
    }
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean,emit1:boolean,emit2:boolean,emit3:boolean,emit4:boolean,emit5:boolean,emit6:boolean,emit7:boolean,emit8:boolean,emit9:boolean,emit10:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.change.subscribe(_eventHandler.bind(view,'change'))); }
    if (emit1) { (this.subscription1 = this.context.onSelecionarItem.subscribe(_eventHandler.bind(view,'onSelecionarItem'))); }
    if (emit2) { (this.subscription2 = this.context.onBuscar.subscribe(_eventHandler.bind(view,'onBuscar'))); }
    if (emit3) { (this.subscription3 = this.context.onApagar.subscribe(_eventHandler.bind(view,'onApagar'))); }
    if (emit4) { (this.subscription4 = this.context.onRemoverItem.subscribe(_eventHandler.bind(view,'onRemoverItem'))); }
    if (emit5) { (this.subscription5 = this.context.onAbrir.subscribe(_eventHandler.bind(view,'onAbrir'))); }
    if (emit6) { (this.subscription6 = this.context.onFechar.subscribe(_eventHandler.bind(view,'onFechar'))); }
    if (emit7) { (this.subscription7 = this.context.onLimpar.subscribe(_eventHandler.bind(view,'onLimpar'))); }
    if (emit8) { (this.subscription8 = this.context.onErro.subscribe(_eventHandler.bind(view,'onErro'))); }
    if (emit9) { (this.subscription9 = this.context.onProcessaResultado.subscribe(_eventHandler.bind(view,'onProcessaResultado'))); }
    if (emit10) { (this.subscription10 = this.context.onProcessaParametros.subscribe(_eventHandler.bind(view,'onProcessaParametros'))); }
  }
}
var renderType_RequestComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_RequestComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.RequestComponent>;
  _RequestComponent_0_3:Wrapper_RequestComponent;
  __NG_VALUE_ACCESSOR_0_4:any[];
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_RequestComponent_Host0,renderType_RequestComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  get _NG_VALUE_ACCESSOR_0_4():any[] {
    if ((this.__NG_VALUE_ACCESSOR_0_4 == null)) { (this.__NG_VALUE_ACCESSOR_0_4 = [this._RequestComponent_0_3.context]); }
    return this.__NG_VALUE_ACCESSOR_0_4;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'select2-request',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_RequestComponent0(this.viewUtils,this,0,this._el_0);
    this._RequestComponent_0_3 = new Wrapper_RequestComponent(new import9.ElementRef(this._el_0),this.injectorGet(import10.NgZone,this.parentIndex),this.injectorGet(import11.SelectService,this.parentIndex),this.renderer);
    this.compView_0.create(this._RequestComponent_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray8(6,'click','document','focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._RequestComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.RequestComponent) && (0 === requestNodeIndex))) { return this._RequestComponent_0_3.context; }
    if (((token === import12.NG_VALUE_ACCESSOR) && (0 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._RequestComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._RequestComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.compView_0.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RequestComponent_0_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
export const RequestComponentNgFactory:import8.ComponentFactory<import0.RequestComponent> = new import8.ComponentFactory<import0.RequestComponent>('select2-request',View_RequestComponent_Host0,import0.RequestComponent);
const styles_RequestComponent:any[] = ([] as any[]);
class View_RequestComponent1 extends import2.AppView<any> {
  _el_0:any;
  _HighlightDirective_0_3:import13.Wrapper_HighlightDirective;
  _text_1:any;
  _el_2:any;
  /*private*/ _vc_2:import14.ViewContainer;
  _InnerTemplateDirective_2_5:import15.Wrapper_InnerTemplateDirective;
  _text_3:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import14.ViewContainer) {
    super(View_RequestComponent1,renderType_RequestComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_7 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',new import3.InlineArray8(6,'class','select2-results__option','highlight','select2-results__option--highlighted','role','treeitem'),(null as any));
    this._HighlightDirective_0_3 = new import13.Wrapper_HighlightDirective(new import9.ElementRef(this._el_0));
    this._text_1 = this.renderer.createText(this._el_0,'\n                                    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_2 = new import14.ViewContainer(2,0,this,this._el_2);
    this._InnerTemplateDirective_2_5 = new import15.Wrapper_InnerTemplateDirective(this._vc_2.vcRef);
    this._text_3 = this.renderer.createText(this._el_0,'\n                                ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray8(6,'click',(null as any),'mouseenter',(null as any),'mouseleave',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.InnerTemplateDirective) && (2 === requestNodeIndex))) { return this._InnerTemplateDirective_2_5.context; }
    if (((token === import17.HighlightDirective) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._HighlightDirective_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = 'select2-results__option--highlighted';
    this._HighlightDirective_0_3.check_classe(currVal_0_0_0,throwOnChange,false);
    this._HighlightDirective_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_2_0_0:any = this.context.$implicit;
    this._InnerTemplateDirective_2_5.check_item(currVal_2_0_0,throwOnChange,false);
    const currVal_2_0_1:any = (this.parentView.context.templateResultado || (<View_RequestComponent0>this.parentView)._TemplateRef_73_4);
    this._InnerTemplateDirective_2_5.check_templateRef(currVal_2_0_1,throwOnChange,false);
    this._InnerTemplateDirective_2_5.ngDoCheck(this,this._el_2,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
    const currVal_7:any = ((this.parentView.context._value && (this.context.$implicit[this.parentView.context.indiceId] == this.parentView.context._value[this.parentView.context.indiceId]))? true: false);
    if (import3.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementAttribute(this._el_0,'aria-selected',((currVal_7 == null)? (null as any): currVal_7.toString()));
      this._expr_7 = currVal_7;
    }
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._HighlightDirective_0_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.selecionar(this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_RequestComponent2 extends import2.AppView<any> {
  _text_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import14.ViewContainer) {
    super(View_RequestComponent2,renderType_RequestComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._text_0 = this.renderer.createText((null as any),'\n        Nenhum resultado encontrado\n    ',(null as any));
    this.init(this._text_0,((<any>this.renderer).directRenderer? (null as any): [this._text_0]),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._text_0,ctx);
  }
}
class View_RequestComponent3 extends import2.AppView<any> {
  _text_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import14.ViewContainer) {
    super(View_RequestComponent3,renderType_RequestComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_1 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._text_0 = this.renderer.createText((null as any),'',(null as any));
    this.init(this._text_0,((<any>this.renderer).directRenderer? (null as any): [this._text_0]),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = import3.inlineInterpolate(1,'\n        ',this.context.$implicit[this.parentView.context.indiceNome],'\n    ');
    if (import3.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_0,currVal_1);
      this._expr_1 = currVal_1;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._text_0,ctx);
  }
}
class View_RequestComponent5 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import14.ViewContainer) {
    super(View_RequestComponent5,renderType_RequestComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import3.inlineInterpolate(1,'\n            ',this.parentView.context.$implicit[this.parentView.parentView.context.indiceNome],'\n        ');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_RequestComponent4 extends import2.AppView<any> {
  _text_0:any;
  _anchor_1:any;
  /*private*/ _vc_1:import14.ViewContainer;
  _TemplateRef_1_5:any;
  _NgIf_1_6:import18.Wrapper_NgIf;
  _text_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import14.ViewContainer) {
    super(View_RequestComponent4,renderType_RequestComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._text_0 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._anchor_1 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._vc_1 = new import14.ViewContainer(1,(null as any),this,this._anchor_1);
    this._TemplateRef_1_5 = new import19.TemplateRef_(this,1,this._anchor_1);
    this._NgIf_1_6 = new import18.Wrapper_NgIf(this._vc_1.vcRef,this._TemplateRef_1_5);
    this._text_2 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.init(this._text_2,((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._anchor_1,
      this._text_2
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.TemplateRef) && (1 === requestNodeIndex))) { return this._TemplateRef_1_5; }
    if (((token === import20.NgIf) && (1 === requestNodeIndex))) { return this._NgIf_1_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1_0_0:any = this.context.$implicit;
    this._NgIf_1_6.check_ngIf(currVal_1_0_0,throwOnChange,false);
    this._NgIf_1_6.ngDoCheck(this,this._anchor_1,throwOnChange);
    this._vc_1.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_1.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._text_0,ctx);
    cb(this._vc_1.nativeElement,ctx);
    this._vc_1.visitNestedViewRootNodes(cb,ctx);
    cb(this._text_2,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 1)) { return new View_RequestComponent5(this.viewUtils,this,1,this._anchor_1,this._vc_1); }
    return (null as any);
  }
}
class View_RequestComponent6 extends import2.AppView<any> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import14.ViewContainer) {
    super(View_RequestComponent6,renderType_RequestComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._text_0 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,(null as any),'span',new import3.InlineArray4(4,'class','fa fa-5x fa-refresh fa-spin','style',' width: auto;margin:auto 50% !important'),(null as any));
    this._text_2 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.init(this._text_2,((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._text_0,ctx);
    cb(this._el_1,ctx);
    cb(this._text_2,ctx);
  }
}
var renderType_RequestComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,styles_RequestComponent,{});
export class View_RequestComponent0 extends import2.AppView<import0.RequestComponent> {
  _viewQuery_campoBusca_0:import21.QueryList<any>;
  _text_0:any;
  _text_1:any;
  _el_2:any;
  _NgClass_2_3:import22.Wrapper_NgClass;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _vc_14:import14.ViewContainer;
  _InnerTemplateDirective_14_5:import15.Wrapper_InnerTemplateDirective;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  _InfiniteScrollDirective_43_3:import23.Wrapper_InfiniteScrollDirective;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _anchor_49:any;
  /*private*/ _vc_49:import14.ViewContainer;
  _TemplateRef_49_5:any;
  _NgFor_49_6:import24.Wrapper_NgFor;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _el_54:any;
  /*private*/ _vc_54:import14.ViewContainer;
  _InnerTemplateDirective_54_5:import15.Wrapper_InnerTemplateDirective;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _el_59:any;
  /*private*/ _vc_59:import14.ViewContainer;
  _InnerTemplateDirective_59_5:import15.Wrapper_InnerTemplateDirective;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  _text_70:any;
  _anchor_71:any;
  /*private*/ _vc_71:import14.ViewContainer;
  _TemplateRef_71_4:any;
  _text_72:any;
  _anchor_73:any;
  /*private*/ _vc_73:import14.ViewContainer;
  _TemplateRef_73_4:any;
  _text_74:any;
  _anchor_75:any;
  /*private*/ _vc_75:import14.ViewContainer;
  _TemplateRef_75_4:any;
  _text_76:any;
  _anchor_77:any;
  /*private*/ _vc_77:import14.ViewContainer;
  _TemplateRef_77_4:any;
  _text_78:any;
  /*private*/ _expr_99:any;
  /*private*/ _expr_100:any;
  /*private*/ _expr_101:any;
  /*private*/ _expr_102:any;
  /*private*/ _expr_103:any;
  /*private*/ _expr_104:any;
  /*private*/ _expr_105:any;
  /*private*/ _expr_106:any;
  /*private*/ _expr_107:any;
  _map_108:any;
  /*private*/ _expr_109:any;
  /*private*/ _expr_110:any;
  /*private*/ _expr_111:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_RequestComponent0,renderType_RequestComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_99 = import1.UNINITIALIZED;
    this._expr_100 = import1.UNINITIALIZED;
    this._expr_101 = import1.UNINITIALIZED;
    this._expr_102 = import1.UNINITIALIZED;
    this._expr_103 = import1.UNINITIALIZED;
    this._expr_104 = import1.UNINITIALIZED;
    this._expr_105 = import1.UNINITIALIZED;
    this._expr_106 = import1.UNINITIALIZED;
    this._expr_107 = import1.UNINITIALIZED;
    this._map_108 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {pesquisa: p0};
    });
    this._expr_109 = import1.UNINITIALIZED;
    this._expr_110 = import1.UNINITIALIZED;
    this._expr_111 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._viewQuery_campoBusca_0 = new import21.QueryList<any>();
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,parentRenderNode,'span',new import3.InlineArray2(2,'dir','ltr'),(null as any));
    this._NgClass_2_3 = new import22.Wrapper_NgClass(this.parentView.injectorGet(import25.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import26.KeyValueDiffers,this.parentIndex),new import9.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'span',new import3.InlineArray2(2,'class','selection'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._text_6 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_4,'span',new import3.InlineArray16(10,'aria-expanded','false','aria-haspopup','true','class','select2-selection select2-selection--single','role','combobox','tabindex','0'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n                ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'span',new import3.InlineArray2(2,'class','select2-selection__rendered'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n                    ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'span',new import3.InlineArray2(2,'class','select2-selection__clear'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'×',(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'\n                    ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_9,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_14 = new import14.ViewContainer(14,9,this,this._el_14);
    this._InnerTemplateDirective_14_5 = new import15.Wrapper_InnerTemplateDirective(this._vc_14.vcRef);
    this._text_15 = this.renderer.createText(this._el_9,'\n                    ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_9,'span',new import3.InlineArray2(2,'class','select2-selection__placeholder'),(null as any));
    this._text_17 = this.renderer.createText(this._el_9,'\n    \n                ',(null as any));
    this._text_18 = this.renderer.createText(this._el_7,'\n                ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_7,'span',new import3.InlineArray4(4,'class','select2-selection__arrow','role','presentation'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n                    ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_19,'b',new import3.InlineArray2(2,'role','presentation'),(null as any));
    this._text_22 = this.renderer.createText(this._el_19,'\n                ',(null as any));
    this._text_23 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._text_24 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_25 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_2,'span',new import3.InlineArray4(4,'aria-hidden','true','class','dropdown-wrapper'),(null as any));
    this._text_27 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_28 = this.renderer.createText(parentRenderNode,'\n    \n    ',(null as any));
    this._text_29 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,parentRenderNode,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'\n        ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_30,'span',new import3.InlineArray2(2,'class','select2-container select2-container--bootstrap select2-container--open'),(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'\n            ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_32,'span',new import3.InlineArray4(4,'class','select2-dropdown select2-dropdown--below','dir','ltr'),(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'\n                ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_34,'span',new import3.InlineArray2(2,'class','select2-search select2-search--dropdown'),(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'\n                    ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_36,'input',new import3.InlineArrayDynamic(20,'autocapitalize','off','autocomplete','off','autocorrect','off','autofocus','','class','select2-search__field','placeholder','Digite algo','role','textbox','spellcheck','false','tabindex','0','type','search'),(null as any));
    this._text_39 = this.renderer.createText(this._el_36,'\n                ',(null as any));
    this._text_40 = this.renderer.createText(this._el_34,'\n                ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_34,'span',new import3.InlineArray8(6,'aria-expanded','true','aria-hidden','false','class','select2-results'),(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'\n                    ',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_41,'ul',new import3.InlineArray16(10,'class','select2-results__options','infinite-scroll','','role','tree','scroll-distance','0,30','style',' overflow: auto!important;'),(null as any));
    this._InfiniteScrollDirective_43_3 = new import23.Wrapper_InfiniteScrollDirective(new import9.ElementRef(this._el_43));
    this._text_44 = this.renderer.createText(this._el_43,'\n                        ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_43,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'\n                            ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_45,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'\n                                ',(null as any));
    this._anchor_49 = this.renderer.createTemplateAnchor(this._el_47,(null as any));
    this._vc_49 = new import14.ViewContainer(49,47,this,this._anchor_49);
    this._TemplateRef_49_5 = new import19.TemplateRef_(this,49,this._anchor_49);
    this._NgFor_49_6 = new import24.Wrapper_NgFor(this._vc_49.vcRef,this._TemplateRef_49_5,this.parentView.injectorGet(import25.IterableDiffers,this.parentIndex),this.ref);
    this._text_50 = this.renderer.createText(this._el_47,'\n                            ',(null as any));
    this._text_51 = this.renderer.createText(this._el_45,'\n                            ',(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_45,'li',new import3.InlineArray4(4,'aria-live','assertive','class','select2-results__option select2-results__message'),(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'\n                                ',(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_52,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_54 = new import14.ViewContainer(54,52,this,this._el_54);
    this._InnerTemplateDirective_54_5 = new import15.Wrapper_InnerTemplateDirective(this._vc_54.vcRef);
    this._text_55 = this.renderer.createText(this._el_52,'\n                            ',(null as any));
    this._text_56 = this.renderer.createText(this._el_45,'\n                            ',(null as any));
    this._el_57 = import3.createRenderElement(this.renderer,this._el_45,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_58 = this.renderer.createText(this._el_57,'\n                                ',(null as any));
    this._el_59 = import3.createRenderElement(this.renderer,this._el_57,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_59 = new import14.ViewContainer(59,57,this,this._el_59);
    this._InnerTemplateDirective_59_5 = new import15.Wrapper_InnerTemplateDirective(this._vc_59.vcRef);
    this._text_60 = this.renderer.createText(this._el_57,'\n                            ',(null as any));
    this._text_61 = this.renderer.createText(this._el_45,'\n                        ',(null as any));
    this._text_62 = this.renderer.createText(this._el_43,'\n                        ',(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,this._el_43,'li',new import3.InlineArray2(2,'class','select2-results__option select2-results__message'),(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'',(null as any));
    this._text_65 = this.renderer.createText(this._el_43,'\n                    ',(null as any));
    this._text_66 = this.renderer.createText(this._el_41,'\n                ',(null as any));
    this._text_67 = this.renderer.createText(this._el_34,'\n            ',(null as any));
    this._text_68 = this.renderer.createText(this._el_32,'\n        ',(null as any));
    this._text_69 = this.renderer.createText(this._el_30,'\n    ',(null as any));
    this._text_70 = this.renderer.createText(parentRenderNode,'\n    \n    \n    \n    ',(null as any));
    this._anchor_71 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_71 = new import14.ViewContainer(71,(null as any),this,this._anchor_71);
    this._TemplateRef_71_4 = new import19.TemplateRef_(this,71,this._anchor_71);
    this._text_72 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._anchor_73 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_73 = new import14.ViewContainer(73,(null as any),this,this._anchor_73);
    this._TemplateRef_73_4 = new import19.TemplateRef_(this,73,this._anchor_73);
    this._text_74 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._anchor_75 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_75 = new import14.ViewContainer(75,(null as any),this,this._anchor_75);
    this._TemplateRef_75_4 = new import19.TemplateRef_(this,75,this._anchor_75);
    this._text_76 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._anchor_77 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_77 = new import14.ViewContainer(77,(null as any),this,this._anchor_77);
    this._TemplateRef_77_4 = new import19.TemplateRef_(this,77,this._anchor_77);
    this._text_78 = this.renderer.createText(parentRenderNode,'\n    \n    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray4(4,'focus',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_2));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_11,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_11));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_38,new import3.InlineArray2(2,'keyup',(null as any)),this.eventHandler(this.handleEvent_38));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_43,new import3.InlineArray4(4,'OnScrollMethod',(null as any),'scroll',(null as any)),this.eventHandler(this.handleEvent_43));
    this._InfiniteScrollDirective_43_3.subscribe(this,this.eventHandler(this.handleEvent_43),true);
    this._viewQuery_campoBusca_0.reset([new import9.ElementRef(this._el_38)]);
    this.context.campoBusca = this._viewQuery_campoBusca_0.first;
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._anchor_49,
      this._text_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._text_69,
      this._text_70,
      this._anchor_71,
      this._text_72,
      this._anchor_73,
      this._text_74,
      this._anchor_75,
      this._text_76,
      this._anchor_77,
      this._text_78
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.InnerTemplateDirective) && (14 === requestNodeIndex))) { return this._InnerTemplateDirective_14_5.context; }
    if (((token === import27.NgClass) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._NgClass_2_3.context; }
    if (((token === import19.TemplateRef) && (49 === requestNodeIndex))) { return this._TemplateRef_49_5; }
    if (((token === import28.NgFor) && (49 === requestNodeIndex))) { return this._NgFor_49_6.context; }
    if (((token === import16.InnerTemplateDirective) && (54 === requestNodeIndex))) { return this._InnerTemplateDirective_54_5.context; }
    if (((token === import16.InnerTemplateDirective) && (59 === requestNodeIndex))) { return this._InnerTemplateDirective_59_5.context; }
    if (((token === import29.InfiniteScrollDirective) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._InfiniteScrollDirective_43_3.context; }
    if (((token === import19.TemplateRef) && (71 === requestNodeIndex))) { return this._TemplateRef_71_4; }
    if (((token === import19.TemplateRef) && (73 === requestNodeIndex))) { return this._TemplateRef_73_4; }
    if (((token === import19.TemplateRef) && (75 === requestNodeIndex))) { return this._TemplateRef_75_4; }
    if (((token === import19.TemplateRef) && (77 === requestNodeIndex))) { return this._TemplateRef_77_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.context.getClassGeral();
    this._NgClass_2_3.check_ngClass(currVal_2_0_0,throwOnChange,false);
    this._NgClass_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_14_0_0:any = this.context.data;
    this._InnerTemplateDirective_14_5.check_item(currVal_14_0_0,throwOnChange,false);
    const currVal_14_0_1:any = (this.context.templateSelecionado || this._TemplateRef_75_4);
    this._InnerTemplateDirective_14_5.check_templateRef(currVal_14_0_1,throwOnChange,false);
    this._InnerTemplateDirective_14_5.ngDoCheck(this,this._el_14,throwOnChange);
    const currVal_43_0_0:any = '0,30';
    this._InfiniteScrollDirective_43_3.check_scrollTrigger(currVal_43_0_0,throwOnChange,false);
    this._InfiniteScrollDirective_43_3.ngDoCheck(this,this._el_43,throwOnChange);
    const currVal_49_0_0:any = this.context.valoresExibir;
    this._NgFor_49_6.check_ngForOf(currVal_49_0_0,throwOnChange,false);
    this._NgFor_49_6.ngDoCheck(this,this._anchor_49,throwOnChange);
    const currVal_54_0_0:any = this._map_108(this.context.valorPesquisado);
    this._InnerTemplateDirective_54_5.check_item(currVal_54_0_0,throwOnChange,false);
    const currVal_54_0_1:any = (this.context.templateSemResultado || this._TemplateRef_71_4);
    this._InnerTemplateDirective_54_5.check_templateRef(currVal_54_0_1,throwOnChange,false);
    this._InnerTemplateDirective_54_5.ngDoCheck(this,this._el_54,throwOnChange);
    const currVal_59_0_0:any = (this.context.templateBuscando || this._TemplateRef_77_4);
    this._InnerTemplateDirective_59_5.check_templateRef(currVal_59_0_0,throwOnChange,false);
    this._InnerTemplateDirective_59_5.ngDoCheck(this,this._el_59,throwOnChange);
    this._vc_14.detectChangesInNestedViews(throwOnChange);
    this._vc_49.detectChangesInNestedViews(throwOnChange);
    this._vc_54.detectChangesInNestedViews(throwOnChange);
    this._vc_59.detectChangesInNestedViews(throwOnChange);
    this._vc_71.detectChangesInNestedViews(throwOnChange);
    this._vc_73.detectChangesInNestedViews(throwOnChange);
    this._vc_75.detectChangesInNestedViews(throwOnChange);
    this._vc_77.detectChangesInNestedViews(throwOnChange);
    const currVal_99:any = this.context.tabIndex;
    if (import3.checkBinding(throwOnChange,this._expr_99,currVal_99)) {
      this.renderer.setElementProperty(this._el_2,'tabIndex',currVal_99);
      this._expr_99 = currVal_99;
    }
    const currVal_100:boolean = !this.context.data;
    if (import3.checkBinding(throwOnChange,this._expr_100,currVal_100)) {
      this.renderer.setElementProperty(this._el_11,'hidden',currVal_100);
      this._expr_100 = currVal_100;
    }
    const currVal_101:boolean = !this.context.data;
    if (import3.checkBinding(throwOnChange,this._expr_101,currVal_101)) {
      this.renderer.setElementProperty(this._el_14,'hidden',currVal_101);
      this._expr_101 = currVal_101;
    }
    const currVal_102:any = this.context.data;
    if (import3.checkBinding(throwOnChange,this._expr_102,currVal_102)) {
      this.renderer.setElementProperty(this._el_16,'hidden',currVal_102);
      this._expr_102 = currVal_102;
    }
    const currVal_103:any = this.context.placeholder;
    if (import3.checkBinding(throwOnChange,this._expr_103,currVal_103)) {
      this.renderer.setElementProperty(this._el_16,'innerHTML',this.viewUtils.sanitizer.sanitize(import30.SecurityContext.HTML,currVal_103));
      this._expr_103 = currVal_103;
    }
    const currVal_104:boolean = !this.context.aberto;
    if (import3.checkBinding(throwOnChange,this._expr_104,currVal_104)) {
      this.renderer.setElementProperty(this._el_30,'hidden',currVal_104);
      this._expr_104 = currVal_104;
    }
    const currVal_105:any = this.context.exibirMensagemCaracteresMinimo;
    if (import3.checkBinding(throwOnChange,this._expr_105,currVal_105)) {
      this.renderer.setElementProperty(this._el_45,'hidden',currVal_105);
      this._expr_105 = currVal_105;
    }
    const currVal_106:any = (this.context.exibirMensagemCaracteresMinimo && (this.context.valoresExibir.length == 0));
    if (import3.checkBinding(throwOnChange,this._expr_106,currVal_106)) {
      this.renderer.setElementProperty(this._el_47,'hidden',currVal_106);
      this._expr_106 = currVal_106;
    }
    const currVal_107:any = (this.context.buscando || (this.context.valoresExibir.length > 0));
    if (import3.checkBinding(throwOnChange,this._expr_107,currVal_107)) {
      this.renderer.setElementProperty(this._el_52,'hidden',currVal_107);
      this._expr_107 = currVal_107;
    }
    const currVal_109:boolean = !this.context.buscando;
    if (import3.checkBinding(throwOnChange,this._expr_109,currVal_109)) {
      this.renderer.setElementProperty(this._el_57,'hidden',currVal_109);
      this._expr_109 = currVal_109;
    }
    const currVal_110:any = (this.context.exibirMensagemCaracteresMinimo == false);
    if (import3.checkBinding(throwOnChange,this._expr_110,currVal_110)) {
      this.renderer.setElementProperty(this._el_63,'hidden',currVal_110);
      this._expr_110 = currVal_110;
    }
    const currVal_111:any = import3.inlineInterpolate(1,'\n                            Digite ',this.context.minimoCaracteres,' ou mais caracteres para realizar a busca\n                        ');
    if (import3.checkBinding(throwOnChange,this._expr_111,currVal_111)) {
      this.renderer.setText(this._text_64,currVal_111);
      this._expr_111 = currVal_111;
    }
  }
  destroyInternal():void {
    this._vc_14.destroyNestedViews();
    this._vc_49.destroyNestedViews();
    this._vc_54.destroyNestedViews();
    this._vc_59.destroyNestedViews();
    this._vc_71.destroyNestedViews();
    this._vc_73.destroyNestedViews();
    this._vc_75.destroyNestedViews();
    this._vc_77.destroyNestedViews();
    this._InfiniteScrollDirective_43_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 49)) { return new View_RequestComponent1(this.viewUtils,this,49,this._anchor_49,this._vc_49); }
    if ((nodeIndex == 71)) { return new View_RequestComponent2(this.viewUtils,this,71,this._anchor_71,this._vc_71); }
    if ((nodeIndex == 73)) { return new View_RequestComponent3(this.viewUtils,this,73,this._anchor_73,this._vc_73); }
    if ((nodeIndex == 75)) { return new View_RequestComponent4(this.viewUtils,this,75,this._anchor_75,this._vc_75); }
    if ((nodeIndex == 77)) { return new View_RequestComponent6(this.viewUtils,this,77,this._anchor_77,this._vc_77); }
    return (null as any);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'focus')) {
      const pd_sub_0:any = ((<any>this.context.abrir()) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'click')) {
      const pd_sub_1:any = ((<any>this.context.abrir()) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
  handleEvent_11(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.limpar($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_38(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'keyup')) {
      const pd_sub_0:any = ((<any>this.context.keyup($event.target.value)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_43(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._InfiniteScrollDirective_43_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'OnScrollMethod')) {
      const pd_sub_0:any = ((<any>this.context.onScroll()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}